version: '2.2'

services:
  alfresco:
    image: ${DOCKER_IMAGE:-hub.xenit.eu/object-storage/alfresco}
    volumes:
      - alfresco:/opt/alfresco/alf_data
    ports:
      - 8080
      # - 8000:8000 # DEBUG
    environment:
      # - DEBUG=true
      - INDEX=noindex
      - GLOBAL_system.content.eagerOrphanCleanup=true

  postgresql:
    image: hub.xenit.eu/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco

volumes:
  alfresco:
  postgres:
